name: storage_fields
description: A convenient abstraction over data storage with a flexible dependency system.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  meta: 1.8.0
  collection: 1.16.0
  json_annotation: ^4.4.0
  intl: ^0.17.0
  equatable: ^2.0.3
  rxdart: ^0.27.7
  googleapis: ^10.1.0
  googleapis_auth: ^1.3.1
  recase: ^4.0.0
  gentle_lints:
    git:
      url: git@github.com:GentleTechTeam/GentleLints.git

dev_dependencies:
  test: ^1.16.0
  json_serializable: ^6.1.6
  build_runner: ^2.1.10
